"""initial postgres schema

Revision ID: e654d5aacb16
Revises: 
Create Date: 2026-02-02 09:48:49.634608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e654d5aacb16'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('years_in_business', sa.Integer(), nullable=False),
    sa.Column('annual_revenue', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lender',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_credit',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=True),
    sa.Column('paynet_score', sa.Integer(), nullable=True),
    sa.Column('trade_lines', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lender_program',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lender_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('min_loan_amount', sa.Numeric(), nullable=True),
    sa.Column('max_loan_amount', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['lender_id'], ['lender.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_request',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('equipment_type', sa.String(), nullable=True),
    sa.Column('equipment_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_guarantor',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=True),
    sa.Column('fico_score', sa.Integer(), nullable=False),
    sa.Column('bankruptcy_flag', sa.Boolean(), nullable=True),
    sa.Column('collections_flag', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_result',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('loan_request_id', sa.String(), nullable=True),
    sa.Column('lender_id', sa.String(), nullable=True),
    sa.Column('program_id', sa.String(), nullable=True),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('fit_score', sa.Integer(), nullable=True),
    sa.Column('rejection_reasons', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lender_id'], ['lender.id'], ),
    sa.ForeignKeyConstraint(['loan_request_id'], ['loan_request.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['lender_program.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_criteria',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('program_id', sa.String(), nullable=True),
    sa.Column('criteria_type', sa.String(), nullable=False),
    sa.Column('operator', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['lender_program.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policy_criteria')
    op.drop_table('match_result')
    op.drop_table('personal_guarantor')
    op.drop_table('loan_request')
    op.drop_table('lender_program')
    op.drop_table('business_credit')
    op.drop_table('lender')
    op.drop_table('business')
    # ### end Alembic commands ###
